WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

CREATE TABLE customer_accounts (
    customer_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name     VARCHAR2(200) NOT NULL,
    industry          VARCHAR2(100),
    account_value     NUMBER(14,2),
    risk_score        NUMBER(5,2) NOT NULL,
    risk_level        VARCHAR2(20) NOT NULL,
    risk_summary      VARCHAR2(1000),
    owner_name        VARCHAR2(200),
    follow_up_status  VARCHAR2(30) DEFAULT 'NONE' NOT NULL,
    last_updated      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_customer_risk_score CHECK (risk_score BETWEEN 0 AND 100),
    CONSTRAINT ck_customer_risk_level CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
);

CREATE TABLE customer_risk_events (
    event_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       NUMBER NOT NULL,
    event_type        VARCHAR2(100) NOT NULL,
    event_description VARCHAR2(2000) NOT NULL,
    event_date        TIMESTAMP NOT NULL,
    severity          NUMBER(2) NOT NULL,
    CONSTRAINT ck_risk_event_severity CHECK (severity BETWEEN 1 AND 10),
    CONSTRAINT fk_risk_customer FOREIGN KEY (customer_id)
        REFERENCES customer_accounts(customer_id)
);

CREATE TABLE customer_actions (
    action_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id       NUMBER NOT NULL,
    action_type       VARCHAR2(100) NOT NULL,
    action_notes      VARCHAR2(2000) NOT NULL,
    requested_by      VARCHAR2(200) NOT NULL,
    action_status     VARCHAR2(30) NOT NULL,
    created_at        TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at      TIMESTAMP,
    CONSTRAINT ck_customer_action_type CHECK (action_type IN ('REVIEW', 'CONTACT_OWNER', 'FREEZE_CHANGES')),
    CONSTRAINT ck_customer_action_status CHECK (action_status IN ('APPROVED', 'COMPLETED', 'FAILED')),
    CONSTRAINT fk_action_customer FOREIGN KEY (customer_id)
        REFERENCES customer_accounts(customer_id)
);

CREATE INDEX customer_risk_events_ix1 ON customer_risk_events(customer_id, event_date DESC);
CREATE INDEX customer_actions_ix1 ON customer_actions(customer_id, created_at DESC);
