
-- DROP TABLE IF EXISTS
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE accounts CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/

-- CREATE ACCOUNTS TABLE ak: set account_id as primary key for reservable to avoid ORA-55728
CREATE TABLE "FINANCIAL"."ACCOUNTS"
   (	"ACCOUNT_ID" NUMBER(19,0) PRIMARY KEY,
	"ACCOUNT_BALANCE" NUMBER(19,0) RESERVABLE,
	"CUSTOMER_ID" VARCHAR2(255 CHAR),
	"ACCOUNT_NAME" VARCHAR2(255 CHAR),
	"ACCOUNT_OPENED_DATE" TIMESTAMP (6),
	"ACCOUNT_OTHER_DETAILS" VARCHAR2(255 CHAR),
	"ACCOUNT_TYPE" VARCHAR2(255 CHAR)
   ) ;
